# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2021-03-09 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='super',
            options={'ordering': ['-name', 'code']},
        ),
    ]
